export const salahPhrasesEn: string[] = [
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; open for us the doors of goodness and grace.",
    "O Allah, bless Muhammad; heal our bodies and remove our sorrows.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; resolve our difficulties and fulfill our needs.",
    "O Allah, bless Muhammad; fill our bodies with light and wellness.",
    "O Allah, bless Muhammad; erase our sins and cover our faults.",
    "O Allah, bless Muhammad; lead us from illusion to true understanding.",
    "O Allah, bless Muhammad; grant us Your pleasure and contentment.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us his intercession on Judgment Day.",
    "O Allah, bless Muhammad; bless our lives, provisions, and families.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; expand our wealth and perfect our manners.",
    "O Allah, bless Muhammad; make us content with Your bounty alone.",
    "O Allah, bless Muhammad; open for us the doors of every cause.",
    "O Allah, bless Muhammad; bring us blessings and remove all distress.",
    "O Allah, bless Muhammad; be our fortress from evil and calamities.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; brighten our faces and cover our honor.",
    "O Allah, bless Muhammad; make us among the people of Paradise.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; gather us with the Prophets and the truthful.",
    "O Allah, bless Muhammad; let us cross the Path like lightning to Peace.",
    "O Allah, bless Muhammad; grant us abundance in provision and mercy.",
    "O Allah, bless Muhammad; let this be our salvation and victory.",
    "O Allah, bless Muhammad; grant us the highest level of Paradise.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; open for us the doors of mercy and acceptance.",
    "O Allah, bless Muhammad; bless our lives and our righteous deeds.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; fill our hearts with light and true faith.",
    "O Allah, bless Muhammad; save us from the terrors of Resurrection Day.",
    "O Allah, bless Muhammad; enlighten our insight and open our minds.",
    "O Allah, bless Muhammad; erase our sins and forgive our mistakes.",
    "O Allah, bless Muhammad; pour Your divine treasures upon us.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; a prayer weighing more than the universe.",
    "O Allah, bless Muhammad; a prayer from a soul whose only hope is You.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; the sea of Your lights and our intercessor.",
    "O Allah, bless Muhammad; a blessed prayer worthy of Your majesty.",
    "O Allah, bless Muhammad; grant us the wisdom of the gnostics.",
    "O Allah, bless Muhammad; polish our hearts and remove our distress.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; fill our time with Your dhikr and thanks.",
    "O Allah, bless Muhammad; free us from the captivity of desires.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; protect us from evil and grant us refuge.",
    "O Allah, bless Muhammad; purify our manners and calm our fears.",
    "O Allah, bless Muhammad; guide our hearts and fix our affairs.",
    "O Allah, bless Muhammad; help us obey You and be our fortress.",
    "O Allah, bless Muhammad; bring down Your mercy and remove afflictions.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; a prayer that pleases the Most Merciful.",
    "O Allah, bless Muhammad; remove our distress and mend our hearts.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us perfect sincerity and certainty.",
    "O Allah, bless Muhammad; a radiant prayer that erases our flaws.",
    "O Allah, bless Muhammad; support us with his light in both worlds.",
    "O Allah, bless Muhammad; pay our debts and relieve our worries.",
    "O Allah, bless Muhammad; make us among those who remember and thank.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; convey our love and longing to him.",
    "O Allah, bless Muhammad; lift the affliction and stop the plague.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; guard us from error and guide our deeds.",
    "O Allah, bless Muhammad; open our hearts and forgive our sins.",
    "O Allah, bless Muhammad; fill our lives with blessings and peace.",
    "O Allah, bless Muhammad; bless our homes and enlighten our secrets.",
    "O Allah, bless Muhammad; make us winners of Your pleasure & Paradise.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; cleanse our souls and purify our spirits.",
    "O Allah, bless Muhammad; bring us the best and most general blessings.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; protect us from envy and plots.",
    "O Allah, bless Muhammad; make us among the patient and content.",
    "O Allah, bless Muhammad; enlighten our minds and free our tongues.",
    "O Allah, bless Muhammad; lead us from doubt to certainty and guidance.",
    "O Allah, bless Muhammad; let this be a shield from the Hellfire.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless our families and our descendants.",
    "O Allah, bless Muhammad; remove the love of this world from our hearts.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us Your pardon and sweet communion.",
    "O Allah, bless Muhammad; make us follow the best and fear You.",
    "O Allah, bless Muhammad; fill our souls with peace and tranquility.",
    "O Allah, bless Muhammad; heal our sick and have mercy on our dead.",
    "O Allah, bless Muhammad; a prayer beyond count or measure.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; open the gates of Heaven with acceptance.",
    "O Allah, bless Muhammad; purify our understanding and beautify us.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make our love for him above all love.",
    "O Allah, bless Muhammad; save us from darkness into the light.",
    "O Allah, bless Muhammad; fill the horizons with light and goodness.",
    "O Allah, bless Muhammad; be our light in the grave and Resurrection.",
    "O Allah, bless Muhammad; let us feel his peace in our hearts.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; protect our bodies from illnesses.",
    "O Allah, bless Muhammad; make us among the joyful faces meeting You.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us perfect manners and respect.",
    "O Allah, bless Muhammad; bless our lives until we meet You.",
    "O Allah, bless Muhammad; open our eyes to the truth and guidance.",
    "O Allah, bless Muhammad; let us be mentioned in the Highest Assembly.",
    "O Allah, bless Muhammad; perfume our souls and sittings with dhikr.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us strong will and true trust.",
    "O Allah, bless Muhammad; unite us and fix our current state.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make us racers to goodness and blessings.",
    "O Allah, bless Muhammad; shower us with Your vast mercy and bounty.",
    "O Allah, bless Muhammad; be our shield from Satan and sorrows.",
    "O Allah, bless Muhammad; bring us to the company of the righteous.",
    "O Allah, bless Muhammad; increase our longing to stand before You.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; expand our hearts and ease our affairs.",
    "O Allah, bless Muhammad; bless our provisions and save us from trials.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us perfect certainty and piety.",
    "O Allah, bless Muhammad; remove our distress and fix our state.",
    "O Allah, bless Muhammad; open for us the doors of happiness.",
    "O Allah, bless Muhammad; grant us perfect wellness and protection.",
    "O Allah, bless Muhammad; raise our status and ease our hardship.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; make us humble rememberers in the night.",
    "O Allah, bless Muhammad; bless every step we take for Your sake.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; protect our hearts from going astray.",
    "O Allah, bless Muhammad; be our intercessor on Judgment Day.",
    "O Allah, bless Muhammad; fill existence with blessings and love.",
    "O Allah, bless Muhammad; a prayer connected to Your eternal bounty.",
    "O Allah, bless Muhammad; let us drink from his Fountain.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless our deeds and accept our prayers.",
    "O Allah, bless Muhammad; remove our worries and bring us joy.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us honesty and sincerity in action.",
    "O Allah, bless Muhammad; save us from the grave and Resurrection.",
    "O Allah, bless Muhammad; light our path and comfort our loneliness.",
    "O Allah, bless Muhammad; bless our health and lengthen our lives.",
    "O Allah, bless Muhammad; make us among Your close and content allies.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; open our hearts and tongues for dhikr.",
    "O Allah, bless Muhammad; gather us in Paradise with the Prophets.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; fill our hearts with contentment.",
    "O Allah, bless Muhammad; guard us from trials and evil of the soul.",
    "O Allah, bless Muhammad; make us true followers of his Sunnah.",
    "O Allah, bless Muhammad; bless our time and keep us in obedience.",
    "O Allah, bless Muhammad; grant us contentment and detachment.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; polish our hearts and light our paths.",
    "O Allah, bless Muhammad; make us among the people of the Quran.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; help us in righteousness and piety.",
    "O Allah, bless Muhammad; bless our homes with Your dhikr.",
    "O Allah, bless Muhammad; grant us perfect manners and purity.",
    "O Allah, bless Muhammad; lift the affliction from the Ummah.",
    "O Allah, bless Muhammad; make us grateful for Your favors.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; fill our souls with peace and wisdom.",
    "O Allah, bless Muhammad; be a key to good and a lock for evil.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; bless our efforts and grant us success.",
    "O Allah, bless Muhammad; grant us deep insight and high ambition.",
    "O Allah, bless Muhammad; let us win the vision of Your Face.",
    "O Allah, bless Muhammad; fill the world with mercy and acceptance.",
    "O Allah, bless Muhammad; protect us and our children from evil.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us perfect following of his morals.",
    "O Allah, bless Muhammad; enlighten our insight and keep us firm.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; bless every single atom of our lives.",
    "O Allah, bless Muhammad; grant us intercession, light, and wealth.",
    "O Allah, bless Muhammad; accept our prayers and our good deeds.",
    "O Allah, bless Muhammad; cleanse our hearts from all distress.",
    "O Allah, bless Muhammad; grant us certainty and the taste of faith.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; make us happy in both worlds.",
    "O Allah, bless Muhammad; bless our path in Your pleasure always.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; be our shield and fortress against harm.",
    "O Allah, bless Muhammad; make us among Your beloved servants.",
    "O Allah, bless Muhammad; fill our scales and make us winners.",
    "O Allah, bless Muhammad; bless our provision and our charity.",
    "O Allah, bless Muhammad; grant us wisdom and correct speech.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; raise our status in both worlds.",
    "O Allah, bless Muhammad; be our light in the grave and Gathering.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make us content with Your decree.",
    "O Allah, bless Muhammad; bless our knowledge and our work.",
    "O Allah, bless Muhammad; grant us health in our bodies.",
    "O Allah, bless Muhammad; open for us the doors of grace.",
    "O Allah, bless Muhammad; free us from the Fire of Hell.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless our families with piety.",
    "O Allah, bless Muhammad; grant us status and salvation.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make us among those who glorify You.",
    "O Allah, bless Muhammad; bless our time and our actions.",
    "O Allah, bless Muhammad; grant us perfect peace and certainty.",
    "O Allah, bless Muhammad; open for us Your vast treasures.",
    "O Allah, bless Muhammad; keep us firm on the truth and guidance.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless every effort made for Your sake.",
    "O Allah, bless Muhammad; grant us understanding of Your word.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make us beloved on earth and in Heaven.",
    "O Allah, bless Muhammad; bless our lives and grant us a good end.",
    "O Allah, bless Muhammad; grant us victory over our desires.",
    "O Allah, bless Muhammad; shade us under Your Throne.",
    "O Allah, bless Muhammad; bless those who follow his message.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us beautiful protection and cover.",
    "O Allah, bless Muhammad; make us among those who trust You fully.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; expand our hearts and forgive our sins.",
    "O Allah, bless Muhammad; make us among the people of sincerity.",
    "O Allah, bless Muhammad; bless our strength for Your obedience.",
    "O Allah, bless Muhammad; grant us chastity and spiritual wealth.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; make us among those who remember You much.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us success and ease in all good.",
    "O Allah, bless Muhammad; make us among those seeking forgiveness.",
    "O Allah, bless Muhammad; bless our time and our deeds.",
    "O Allah, bless Muhammad; grant us perfect monotheism.",
    "O Allah, bless Muhammad; make us among those close to You.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless our travels and keep us safe.",
    "O Allah, bless Muhammad; grant us the power to be patient.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make us among the generous and noble.",
    "O Allah, bless Muhammad; bless our voices with Your dhikr.",
    "O Allah, bless Muhammad; keep us away from backbiting and gossip.",
    "O Allah, bless Muhammad; make us truly sincere with You.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; give us strength to fulfill our trusts.",
    "O Allah, bless Muhammad; make us always winners of Your love.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us humility, kindness, and pardon.",
    "O Allah, bless Muhammad; make us quick to do good deeds.",
    "O Allah, bless Muhammad; bless the upbringing of our children.",
    "O Allah, bless Muhammad; grant us firm faith in the grave.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; make us true followers of his path.",
    "O Allah, bless Muhammad; bless our prayers, charity, and Hajj.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us honor in both worlds.",
    "O Allah, bless Muhammad; let us be intercessors for others.",
    "O Allah, bless Muhammad; bless our provisions.",
    "O Allah, bless Muhammad; grant us Your love and intimacy.",
    "O Allah, bless Muhammad; make us reflect on Your signs.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless our gatherings with dignity.",
    "O Allah, bless Muhammad; grant us loyalty to his family.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; keep us safe from fear and grief.",
    "O Allah, bless Muhammad; bless our pens and what we write.",
    "O Allah, bless Muhammad; grant us courage in the truth.",
    "O Allah, bless Muhammad; make us happy in Your Gardens.",
    "O Allah, bless Muhammad; bless every breath we take with dhikr.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us protection from every eye.",
    "O Allah, bless Muhammad; make us walk with dignity and peace.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; bless our awareness and wisdom.",
    "O Allah, bless Muhammad; save us from the trials of the Antichrist.",
    "O Allah, bless Muhammad; make us people of excellence.",
    "O Allah, bless Muhammad; bless our steps to the mosques.",
    "O Allah, bless Muhammad; grant us the power of forgiveness.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; let us reach the month of Ramadan.",
    "O Allah, bless Muhammad; bless our families and descendants.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us contentment with Your bounty.",
    "O Allah, bless Muhammad; make us sincere in following him.",
    "O Allah, bless Muhammad; bless us with health and wellness.",
    "O Allah, bless Muhammad; grant us victory in Paradise.",
    "O Allah, bless Muhammad; make us among the smiling faces.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless us in our provisions.",
    "O Allah, bless Muhammad; grant us steadfastness in action.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make us heirs of the Garden of Bliss.",
    "O Allah, bless Muhammad; bless every good deed we do.",
    "O Allah, bless Muhammad; grant us dignity, awe, and kindness.",
    "O Allah, bless Muhammad; make us thankful for Your gifts.",
    "O Allah, bless Muhammad; bless our days with piety.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us salvation from all evil.",
    "O Allah, bless Muhammad; make us among those chosen for good.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; bless our hearts and our love for him.",
    "O Allah, bless Muhammad; grant us perfect servitude to You.",
    "O Allah, bless Muhammad; grant us the vision of him in dreams.",
    "O Allah, bless Muhammad; bless every matter of our lives.",
    "O Allah, bless Muhammad; grant us contentment with Your decree.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; make us people of purity.",
    "O Allah, bless Muhammad; bless our times of worship.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us beautiful cover in both worlds.",
    "O Allah, bless Muhammad; make us among those whose prayers are heard.",
    "O Allah, bless Muhammad; bless our journey to You with success.",
    "O Allah, bless Muhammad; grant us perfect faith and gratitude.",
    "O Allah, bless Muhammad; make us among the generous and noble.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless our knowledge and status.",
    "O Allah, bless Muhammad; grant us steadfastness and safety.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; shade us under Your Great Throne.",
    "O Allah, bless Muhammad; bless our lives with contentment.",
    "O Allah, bless Muhammad; grant us perfect success and victory.",
    "O Allah, bless Muhammad; make us sincere servants of his guidance.",
    "O Allah, bless Muhammad; bless our righteous actions.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us strength for Your obedience.",
    "O Allah, bless Muhammad; make us among the joyful faces.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; forgive our sins and cover our faults.",
    "O Allah, bless Muhammad; grant us wisdom, peace, and dignity.",
    "O Allah, bless Muhammad; make us winners of Your pleasure.",
    "O Allah, bless Muhammad; bless our time and our children.",
    "O Allah, bless Muhammad; grant us perfect submission to You.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; make us accepted in word and deed.",
    "O Allah, bless Muhammad; bless every word and action we take.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; grant us pardon and lasting wellness.",
    "O Allah, bless Muhammad; make us among those loyal to promises.",
    "O Allah, bless Muhammad; bless all our efforts with success.",
    "O Allah, bless Muhammad; grant us courage in the truth.",
    "O Allah, bless Muhammad; make us happy in meeting You.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; bless our breaths with Your dhikr.",
    "O Allah, bless Muhammad; grant us complete protection.",
    "O Allah, bless Muhammad, the healer of hearts and the light of eyes.",
    "O Allah, bless Muhammad; make us walk with dignity.",
    "O Allah, bless Muhammad; bless our work for Your sake.",
    "O Allah, bless Muhammad; grant us Paradise without account.",
    "O Allah, bless Muhammad; make us rememberers and thankful.",
    "O Allah, bless Muhammad; bless our world.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; protect us from Fire and the grave.",
    "O Allah, bless Muhammad; raise our status in Paradise.",
    "O Allah, bless Muhammad; purify our hearts from shirk and sin.",
    "O Allah, bless Muhammad; benefit us on the Day we meet You.",
    "O Allah, bless Muhammad; make us people of pleasure and bliss.",
    "O Allah, bless Muhammad; forgive our sins and cover our flaws.",
    "O Allah, bless Muhammad & his family as much as Your perfection allows.",
    "O Allah, bless Muhammad; be a light in our graves and scales.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; make us among his intercessors.",
    "O Allah, bless Muhammad & family as You blessed Abraham & his family.",
    "O Allah, bless Muhammad; grant us victory in Paradise.",
    "O Allah, bless Muhammad; make us among the joyful faces.",
];