export const salahPhrasesEn: string[] = [
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that opens doors of good",
  "O Allah, bless Muhammad & his family with a blessing that heals and ends grief",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that unties knots",
  "O Allah, bless Muhammad & his family with a blessing that fills us with light",
  "O Allah, bless Muhammad & his family with a blessing that erases all our sins",
  "O Allah, bless Muhammad & his family with a blessing that brings understanding",
  "O Allah, bless Muhammad & his family with a blessing that pleases You and him",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that grants intercession",
  "O Allah, bless Muhammad & his family with a blessing that prospers our lives",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that improves character",
  "O Allah, bless Muhammad & his family with a blessing making us need only You",
  "O Allah, bless Muhammad & his family with a blessing that opens every door",
  "O Allah, bless Muhammad & his family with a blessing that brings abundance",
  "O Allah, bless Muhammad & his family with a blessing that shields us from ill",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that honors us always",
  "O Allah, bless Muhammad & his family with a blessing that grants us Paradise",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that joins us with saints",
  "O Allah, bless Muhammad & his family with a blessing that leads us to peace",
  "O Allah, bless Muhammad & his family with a blessing of provision and mercy",
  "O Allah, bless Muhammad & his family with a blessing that saves us from Fire",
  "O Allah, bless Muhammad & his family with a blessing that grants us Firdous",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of mercy and acceptance",
  "O Allah, bless Muhammad & his family with a blessing upon our lives and work",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that fills us with faith",
  "O Allah, bless Muhammad & his family with a blessing that saves us from terror",
  "O Allah, bless Muhammad & his family with a blessing that enlightens us",
  "O Allah, bless Muhammad & his family with a blessing that erases every fault",
  "O Allah, bless Muhammad & his family with a blessing of God’s vast bounty",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing weighing more than worlds",
  "O Allah, bless Muhammad & his family with a blessing when we are helpless",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family, the sea of lights and our intercessor",
  "O Allah, bless Muhammad & his family with a blessed prayer for Your Majesty",
  "O Allah, bless Muhammad & his family with a blessing of true knowledge",
  "O Allah, bless Muhammad & his family with a blessing that clears heart-rust",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that fills our time",
  "O Allah, bless Muhammad & his family with a blessing that frees us from lust",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that guards from evil",
  "O Allah, bless Muhammad & his family with a blessing that purifies our soul",
  "O Allah, bless Muhammad & his family with a blessing that fulfills all hopes",
  "O Allah, bless Muhammad & his family with a blessing that helps us obey You",
  "O Allah, bless Muhammad & his family with a blessing that brings down mercy",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that fills the scales",
  "O Allah, bless Muhammad & his family with a blessing that fixes our affairs",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of total sincerity",
  "O Allah, bless Muhammad & his family with a blessing that erases bad traits",
  "O Allah, bless Muhammad & his family with a blessing of light in both worlds",
  "O Allah, bless Muhammad & his family with a blessing that pays our debts",
  "O Allah, bless Muhammad & his family with a blessing making us truly grateful",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of love for his way",
  "O Allah, bless Muhammad & his family with a blessing that removes afflictions",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that keeps us from error",
  "O Allah, bless Muhammad & his family with a blessing that opens locked hearts",
  "O Allah, bless Muhammad & his family with a blessing of peace and certainty",
  "O Allah, bless Muhammad & his family with a blessing that prospers our homes",
  "O Allah, bless Muhammad & his family with a blessing that grants us Paradise",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that purifies souls",
  "O Allah, bless Muhammad & his family with a blessing that brings all good",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that shields from envy",
  "O Allah, bless Muhammad & his family with a blessing of patience and content",
  "O Allah, bless Muhammad & his family with a blessing that enlightens minds",
  "O Allah, bless Muhammad & his family with a blessing of truth and guidance",
  "O Allah, bless Muhammad & his family with a blessing that veils us from Fire",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing upon our descendants",
  "O Allah, bless Muhammad & his family with a blessing that ends love of world",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of Your sweet pardon",
  "O Allah, bless Muhammad & his family with a blessing that makes us followers",
  "O Allah, bless Muhammad & his family with a blessing of peace in our souls",
  "O Allah, bless Muhammad & his family with a blessing that heals the sick",
  "O Allah, bless Muhammad & his family with a blessing beyond any count",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that opens Heaven",
  "O Allah, bless Muhammad & his family with a blessing that purifies thoughts",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing making him our true love",
  "O Allah, bless Muhammad & his family with a blessing that leads to guidance",
  "O Allah, bless Muhammad & his family with a blessing that fills us with good",
  "O Allah, bless Muhammad & his family with a blessing of light in our graves",
  "O Allah, bless Muhammad & his family with a blessing of joy in our hearts",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that protects our bodies",
  "O Allah, bless Muhammad & his family with a blessing that makes us radiant",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of respect for his rank",
  "O Allah, bless Muhammad & his family with a blessing until we meet You",
  "O Allah, bless Muhammad & his family with a blessing that shows us the truth",
  "O Allah, bless Muhammad & his family with a blessing mentioned in the Heavens",
  "O Allah, bless Muhammad & his family with a blessing that sweetens our breath",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of strong resolve",
  "O Allah, bless Muhammad & his family with a blessing that unites our hearts",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing to lead in good deeds",
  "O Allah, bless Muhammad & his family with a blessing of Your vast mercy",
  "O Allah, bless Muhammad & his family with a blessing shielding us from Satan",
  "O Allah, bless Muhammad & his family with a blessing joining us with saints",
  "O Allah, bless Muhammad & his family with a blessing drawing us closer",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that relieves worries",
  "O Allah, bless Muhammad & his family with a blessing that guards our wealth",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of perfect certainty",
  "O Allah, bless Muhammad & his family with a blessing that fixes our affairs",
  "O Allah, bless Muhammad & his family with a blessing of happiness always",
  "O Allah, bless Muhammad & his family with a blessing of health and cover",
  "O Allah, bless Muhammad & his family with a blessing that raises our rank",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of humble worship",
  "O Allah, bless Muhammad & his family with a blessing in our every step",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that guards our hearts",
  "O Allah, bless Muhammad & his family with a blessing of intercession",
  "O Allah, bless Muhammad & his family with a blessing of love in the world",
  "O Allah, bless Muhammad & his family with a blessing of Your endless grace",
  "O Allah, bless Muhammad & his family with a blessing of drinking from his pond",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that accepts our prayer",
  "O Allah, bless Muhammad & his family with a blessing that brings us joy",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of sincere work",
  "O Allah, bless Muhammad & his family with a blessing saving us from the grave",
  "O Allah, bless Muhammad & his family with a blessing that lights our path",
  "O Allah, bless Muhammad & his family with a blessing of long life in worship",
  "O Allah, bless Muhammad & his family with a blessing that makes us Yours",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that opens our hearts",
  "O Allah, bless Muhammad & his family with a blessing joining us in Paradise",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of contentment",
  "O Allah, bless Muhammad & his family with a blessing that guards from trials",
  "O Allah, bless Muhammad & his family with a blessing that makes us followers",
  "O Allah, bless Muhammad & his family with a blessing in all of our time",
  "O Allah, bless Muhammad & his family with a blessing of true contentment",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that clears heart-rust",
  "O Allah, bless Muhammad & his family with a blessing that makes us Your folk",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of piety and virtue",
  "O Allah, bless Muhammad & his family with a blessing in our homes",
  "O Allah, bless Muhammad & his family with a blessing of pure character",
  "O Allah, bless Muhammad & his family with a blessing that removes trials",
  "O Allah, bless Muhammad & his family with a blessing making us grateful",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of peace and wisdom",
  "O Allah, bless Muhammad & his family with a blessing that opens every good",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that makes us succeed",
  "O Allah, bless Muhammad & his family with a blessing of deep insight",
  "O Allah, bless Muhammad & his family with a blessing of seeing Your Face",
  "O Allah, bless Muhammad & his family with a blessing of mercy for all",
  "O Allah, bless Muhammad & his family with a blessing that guards our kids",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of following him",
  "O Allah, bless Muhammad & his family with a blessing that enlightens us",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing in every atom of life",
  "O Allah, bless Muhammad & his family with a blessing of light and mercy",
  "O Allah, bless Muhammad & his family with a blessing that accepts our deeds",
  "O Allah, bless Muhammad & his family with a blessing that washes our hearts",
  "O Allah, bless Muhammad & his family with a blessing of sweet faith",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of eternal happiness",
  "O Allah, bless Muhammad & his family with a blessing in our path to You",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing shielding us from harm",
  "O Allah, bless Muhammad & his family with a blessing that makes us loved",
  "O Allah, bless Muhammad & his family with a blessing of victory in balance",
  "O Allah, bless Muhammad & his family with a blessing in our provision",
  "O Allah, bless Muhammad & his family with a blessing of true wisdom",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that raises our status",
  "O Allah, bless Muhammad & his family with a blessing of light in our graves",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of contentment",
  "O Allah, bless Muhammad & his family with a blessing in our knowledge",
  "O Allah, bless Muhammad & his family with a blessing of health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that opens every good",
  "O Allah, bless Muhammad & his family with a blessing saving us from Fire",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing for our families",
  "O Allah, bless Muhammad & his family with a blessing of rank and success",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of constant praise",
  "O Allah, bless Muhammad & his family with a blessing in our times and acts",
  "O Allah, bless Muhammad & his family with a blessing of perfect peace",
  "O Allah, bless Muhammad & his family with a blessing of Your vast mercy",
  "O Allah, bless Muhammad & his family with a blessing of firm guidance",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing in every effort",
  "O Allah, bless Muhammad & his family with a blessing of true understanding",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing making us loved by all",
  "O Allah, bless Muhammad & his family with a blessing for a good final end",
  "O Allah, bless Muhammad & his family with a blessing of victory over self",
  "O Allah, bless Muhammad & his family with a blessing in Your great Shade",
  "O Allah, bless Muhammad & his family with a blessing of following his way",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of a beautiful veil",
  "O Allah, bless Muhammad & his family with a blessing of total trust in You",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that forgives all sins",
  "O Allah, bless Muhammad & his family with a blessing of truth and loyalty",
  "O Allah, bless Muhammad & his family with a blessing in all our strength",
  "O Allah, bless Muhammad & his family with a blessing of pure modesty",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of constant worship",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of ease and success",
  "O Allah, bless Muhammad & his family with a blessing of dawn-seekers",
  "O Allah, bless Muhammad & his family with a blessing in our time and work",
  "O Allah, bless Muhammad & his family with a blessing of perfect certainty",
  "O Allah, bless Muhammad & his family with a blessing that makes us close",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing guarding our travels",
  "O Allah, bless Muhammad & his family with a blessing of patience and thanks",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of honor and dignity",
  "O Allah, bless Muhammad & his family with a blessing that sweetens speech",
  "O Allah, bless Muhammad & his family with a blessing keeping us from gossip",
  "O Allah, bless Muhammad & his family with a blessing of true sincerity",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of strength and trust",
  "O Allah, bless Muhammad & his family with a blessing that wins Your love",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of true humility",
  "O Allah, bless Muhammad & his family with a blessing that makes us hasten in good",
  "O Allah, bless Muhammad & his family with a blessing for our kids’ souls",
  "O Allah, bless Muhammad & his family with a blessing that guards our graves",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of following his path",
  "O Allah, bless Muhammad & his family with a blessing in all our worship",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of honor and rank",
  "O Allah, bless Muhammad & his family with a blessing of his intercession",
  "O Allah, bless Muhammad & his family with a blessing in our provision",
  "O Allah, bless Muhammad & his family with a blessing of intimacy with You",
  "O Allah, bless Muhammad & his family with a blessing of pondering Your power",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of peace in our homes",
  "O Allah, bless Muhammad & his family with a blessing for his kin and crew",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that ends all sorrow",
  "O Allah, bless Muhammad & his family with a blessing in all that we write",
  "O Allah, bless Muhammad & his family with a blessing of courage in truth",
  "O Allah, bless Muhammad & his family with a blessing of eternal happiness",
  "O Allah, bless Muhammad & his family with a blessing in our every breath",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that protects us",
  "O Allah, bless Muhammad & his family with a blessing of dignity and grace",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of true wisdom",
  "O Allah, bless Muhammad & his family with a blessing that saves from trials",
  "O Allah, bless Muhammad & his family with a blessing of faith and virtue",
  "O Allah, bless Muhammad & his family with a blessing in our path to prayer",
  "O Allah, bless Muhammad & his family with a blessing that makes us forgive",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that reaches Ramadan",
  "O Allah, bless Muhammad & his family with a blessing for our progeny",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of true contentment",
  "O Allah, bless Muhammad & his family with a blessing of sincere love",
  "O Allah, bless Muhammad & his family with a blessing in our wellness",
  "O Allah, bless Muhammad & his family with a blessing of gardens of bliss",
  "O Allah, bless Muhammad & his family with a blessing of joyful faces",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing in our provision",
  "O Allah, bless Muhammad & his family with a blessing of firmness in deed",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing to inherit Paradise",
  "O Allah, bless Muhammad & his family with a blessing in every righteous act",
  "O Allah, bless Muhammad & his family with a blessing of dignity and grace",
  "O Allah, bless Muhammad & his family with a blessing of true gratitude",
  "O Allah, bless Muhammad & his family with a blessing in our days of piety",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing shielding us from harm",
  "O Allah, bless Muhammad & his family with a blessing of a good destiny",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of love for him",
  "O Allah, bless Muhammad & his family with a blessing of perfect worship",
  "O Allah, bless Muhammad & his family with a blessing to see him in dreams",
  "O Allah, bless Muhammad & his family with a blessing in our every affair",
  "O Allah, bless Muhammad & his family with a blessing of contentment",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of pure character",
  "O Allah, bless Muhammad & his family with a blessing in times of worship",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of a beautiful veil",
  "O Allah, bless Muhammad & his family with a blessing for answered prayers",
  "O Allah, bless Muhammad & his family with a blessing for a straight path",
  "O Allah, bless Muhammad & his family with a blessing of faith and thanks",
  "O Allah, bless Muhammad & his family with a blessing of generosity",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of knowledge and rank",
  "O Allah, bless Muhammad & his family with a blessing that keeps us firm",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing in Your Great Shade",
  "O Allah, bless Muhammad & his family with a blessing of life and content",
  "O Allah, bless Muhammad & his family with a blessing of total success",
  "O Allah, bless Muhammad & his family with a blessing of sincere guidance",
  "O Allah, bless Muhammad & his family with a blessing in our good deeds",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of strength to obey",
  "O Allah, bless Muhammad & his family with a blessing of radiant faces",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing that erases all sins",
  "O Allah, bless Muhammad & his family with a blessing of wisdom and peace",
  "O Allah, bless Muhammad & his family with a blessing of Your good pleasure",
  "O Allah, bless Muhammad & his family with a blessing for our children",
  "O Allah, bless Muhammad & his family with a blessing of perfect surrender",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing that makes us accepted",
  "O Allah, bless Muhammad & his family with a blessing in every word and act",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of wellness and mercy",
  "O Allah, bless Muhammad & his family with a blessing of loyalty and truth",
  "O Allah, bless Muhammad & his family with a blessing for all our efforts",
  "O Allah, bless Muhammad & his family with a blessing of courage in truth",
  "O Allah, bless Muhammad & his family with a blessing of happiness always",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of constant praise",
  "O Allah, bless Muhammad & his family with a blessing of total protection",
  "O Allah, bless Muhammad, the medicine for hearts and health for bodies",
  "O Allah, bless Muhammad & his family with a blessing of walking in guidance",
  "O Allah, bless Muhammad & his family with a blessing in our work for You",
  "O Allah, bless Muhammad & his family with a blessing of Paradise for free",
  "O Allah, bless Muhammad & his family with a blessing of gratitude and hope",
  "O Allah, bless Muhammad & his family with a blessing in our world",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing saving us from Fire",
  "O Allah, bless Muhammad & his family with a blessing raising our rank high",
  "O Allah, bless Muhammad & his family with a blessing that purifies hearts",
  "O Allah, bless Muhammad & his family with a blessing helping us on Your Day",
  "O Allah, bless Muhammad & his family with a blessing of peace and bliss",
  "O Allah, bless Muhammad & his family with a blessing that erases all sins",
  "O Allah, bless Muhammad & his family with a blessing matching Your perfection",
  "O Allah, bless Muhammad & his family with a blessing lighting our graves",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of his intercession",
  "O Allah, bless Muhammad & his family as You blessed Ibrahim and his family",
  "O Allah, bless Muhammad & his family with a blessing of gardens of bliss",
  "O Allah, bless Muhammad & his family with a blessing of joyful faces",
];
